apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: iqs-positron
  name: iqs-bundles-history-node-deploy
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: iqs-bundles-history-node
    spec: 
      containers:
      - name: iqs-bundles-history-node-pod
        image: registry.gitlab.com/iqs-bundles/iqs-bundles-history-node:1.0.0-1-rc
        ports:
        - containerPort: 8080
          name: history
        env:
        - name: ENV_NAME
          valueFrom:
            configMapKeyRef:
              name: iqs-positron-config
              key: env_name
        - name: MONGO_ENABLED
          valueFrom:
            configMapKeyRef:
              name: iqs-positron-config
              key: mongo_enabled
        - name: MONGO_SERVICE_URI
          valueFrom:
            secretKeyRef:
              name: iqs-positron-secret
              key: mongo_service_uri
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: iqs-positron-secret
              key: aws_region
        - name: AWS_ACCESS_ID
          valueFrom:
            secretKeyRef:
              name: iqs-positron-secret
              key: aws_access_id
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: iqs-positron-secret
              key: aws_access_key
        livenessProbe:
          httpGet:
            path: /heartbeat
            port: 8080
          initialDelaySeconds: 180
          periodSeconds: 60
          timeoutSeconds: 10
      imagePullSecrets:
      - name: gitlab-docker-registry
---
apiVersion: v1
kind: Service
metadata:
  namespace: iqs-positron
  name: iqs-bundles-history
  labels: 
    app: iqs-bundles-history-node
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30022
    protocol: TCP
    name: history
  selector:
    app: iqs-bundles-history-node